# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download Beef
        shell: powershell
        run: Start-BitsTransfer -Source "https://nightly.beeflang.org/BeefSetup.exe" -Destination "BeefBuild.exe"
      
      - name: Extract Beef
        shell: cmd
        run: 7z x BeefBuild.exe -oBeef
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      
      - name: Install TOML through Pip
        shell: cmd
        run: pip install toml
      
      - name: Modify BeefSpace.toml to point to local dependencies
        shell: cmd
        run: python .github/modify_beefspace.py
      
      - name: Build
        shell: cmd
        run: Beef/bin/BeefBuild.exe -config=Release
      
      - name: List files
        shell: cmd
        run: ls build/Release_Win64
